# Generated by Django 2.2.12 on 2020-06-11 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('about', models.CharField(max_length=100, null=True)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('datatype', models.CharField(blank=True, max_length=9)),
                ('location_name', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=12, null=True)),
                ('longitude', models.CharField(max_length=13, null=True)),
                ('damage_reported', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('drought_condition', models.TextField(null=True)),
                ('county_basin_withdrawal', models.CharField(max_length=100, null=True)),
                ('surface_water_withdrawal_volume', models.IntegerField(max_length=3, null=True)),
                ('ground_water_withdrawal_volume', models.IntegerField(max_length=3, null=True)),
                ('ground_water_level', models.IntegerField(max_length=7, null=True)),
                ('reported_use_by_sector', models.IntegerField(max_length=7, null=True)),
                ('number_of_intakes', models.IntegerField(max_length=3, null=True)),
                ('surface_water_withdrawal', models.IntegerField(max_length=3, null=True)),
                ('ground_water_withdrawal', models.IntegerField(max_length=3, null=True)),
                ('type_of_crop', models.CharField(max_length=50, null=True)),
                ('total_acers_irrigated', models.IntegerField(max_length=7, null=True)),
                ('total_acers_per_crop_irrigated', models.IntegerField(max_length=7, null=True)),
                ('irrigation_type', models.CharField(max_length=100, null=True)),
                ('power_requirements', models.TextField(max_length=7, null=True)),
                ('irrigation_schedule_info', models.TextField(null=True)),
                ('flood_condition', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
